package com.example.medicalinventryapp.network.Response.productresponses.getAllrpoductsResponse

import com.example.medicalinventryapp.network.Response.productresponses.getAllrpoductsResponse.GetAllProductsResponseItem

class GetAllProductsResponse : ArrayList<GetAllProductsResponseItem>()